name: Update VPN Subs Automatically

on:
  schedule:
    # Chạy vào phút thứ 0 của mỗi 5 tiếng (0:00, 5:00, 10:00...)
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  update-subs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests pyyaml

      - name: Run Script
        run: python update_sub.py
